# Generated by Django 4.2.2 on 2023-06-27 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_user_id_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='my post', validators=[django.core.validators.MinLengthValidator(5, 'your post needs at least 5 characters')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, 'your title needs at least 1 character')]),
        ),
    ]
