# Generated by Django 4.2.2 on 2023-06-27 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_body_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.MinLengthValidator(1, 'your title needs at least 1 character')]),
        ),
    ]
