# Generated by Django 4.2.2 on 2023-07-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postfile_delete_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfile',
            old_name='upload_by',
            new_name='uploaded_by',
        ),
    ]
