# Generated by Django 4.2.2 on 2023-07-05 16:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_rename_upload_by_postfile_uploaded_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFile',
            new_name='File',
        ),
    ]
