# Generated by Django 4.2.2 on 2023-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(max_length=2048),
        ),
    ]
