# Generated by Django 4.2.2 on 2023-07-12 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(5, 'your post needs at least 5 characters')]),
        ),
    ]
