# Generated by Django 4.2.2 on 2023-07-12 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(5, 'your post needs at least 5 characters'), django.core.validators.MaxLengthValidator(5000, 'your post can only have 5000 characters')]),
        ),
    ]
