# Generated by Django 4.2.2 on 2023-07-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_comment_edited_comment_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='edited',
            new_name='is_edited',
        ),
    ]
