# Generated by Django 4.2.2 on 2023-07-12 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_about_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200, 'your about can only have 200 characters')]),
        ),
    ]
