# Generated by Django 4.2.2 on 2023-07-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_rename_edited_comment_is_edited'),
        ('accounts', '0007_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
    ]
