# Generated by Django 4.2.2 on 2023-07-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alert_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_comment_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
